export const INNGEST_MODULE_OPTIONS = 'INNGEST_MODULE_OPTIONS';
export const INNGEST_CLIENT = 'INNGEST_CLIENT';
export const INNGEST_FUNCTION_METADATA = 'INNGEST_FUNCTION_METADATA';
export const INNGEST_MIDDLEWARE_METADATA = 'INNGEST_MIDDLEWARE_METADATA';
export const INNGEST_HANDLER_METADATA = 'INNGEST_HANDLER_METADATA';
